version: '2'
services:
  back:
    build: ./quero-vaga-back
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env.local
  db:
    image: postgres
    ports:
      - "15432:5432"
    env_file:
      - .env.local
  front:
    build: ./quero-vaga-front
    ports:
      - "3001:3000"
    links:
      - back
    depends_on:
      - back
    env_file:
      - .env.local
